server:
  port: 8111
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my-spring-security?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 1234
  mvc:
    view:
      prefix: /templates/
      suffix: .html
mybatis:
  type-aliases-package: com.nzo.entry